language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - 'nightly'
  - 'pypy'
  - 'pypy3'
install:
    # Commented out to check if Travis does what I think it does.
    - './setup.py sdist'
    - 'pip install dist/pytest_reorder-*.tar.gz'
    - 'pip install -e ".[tests]"'
script:
    - 'pylama'
    # Make sure we're using the installed library, not the one from the project root.
    # There is a better way but I dislike having the additional 'src' dir:
    - 'rm pytest_reorder -r'
    - 'py.test -vvvv --showlocals'
sudo: false
